version: '3.8'

services:
  app:
    build: .
    container_name: certification_service
    ports:
      - "${APP_PORT}:5002"
    environment:
      - MONGO_USERNAME=${MONGO_USERNAME}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
      - MONGO_DATABASE=${MONGO_DATABASE}
      - CERTIFICATES_DIR=/app/certificates
      - PFX_PASSPHRASE=mysecurepassphrase
      - SIGNATURE_FIELD_NAME=Signature1
      - SIGNATURE_BOX=150,30,450,90
      - QR_CODE_URL=https://www.youtube.com/watch?v=dQw4w9WgXcQ
    volumes:
      - ./certificates:/app/certificates
    depends_on:
      mongodb:
        condition: service_healthy

  mongodb:
    image: mongo:latest
    container_name: certification_mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE}
    ports:
      - "${MONGO_PORT}:27017"
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh:ro
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
    command: mongod --auth

volumes:
  mongodb_data:
