version: '3.8'

services:
  app:
    build: .
    container_name: certification_service
    environment:
      - MONGO_DATABASE=certificate_db
      - MONGO_PORT=27017
      - MONGO_HOST=teachme-certification-c.oh7xd.mongodb.net
      - MONGO_COLLECTION_NAME=student_certificates
      - MONGO_USERNAME=teachme-certification-service
      - MONGO_PASSWORD=yWYuw4Vj6ARlfD4m
      - MONGODB_URI_USER=mongodb+srv://teachme-certification-service:yWYuw4Vj6ARlfD4m@teachme-certification-c.oh7xd.mongodb.net/?retryWrites=true&w=majority&appName=teachme-certification-cluster
      - AZURE_STORAGE_ACCOUNT_NAME=devstoreaccount1
      - AZURE_STORAGE_ACCOUNT_KEY=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==
      - BLOB_STORAGE_CONTAINER_NAME=certificates
      - BLOB_STORAGE_CONNECTION_STRING=DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://azurite:10000/devstoreaccount1;
      - CERTIFICATES_DIR=/app/certificates
      - PFX_PASSPHRASE=mysecurepassphrase
      - SIGNATURE_FIELD_NAME=Signature1
      - SIGNATURE_BOX=150,30,450,90
      - QR_CODE_URL=https://www.youtube.com/watch?v=dQw4w9WgXcQ
      - MONGODB_URI_ADMIN=mongodb://admin:rootpassword123@mongodb:27017/certificate_db?authSource=admin
    ports:
      - "8080:8080"
    volumes:
      - ./certificates:/app/certificates
    depends_on:
      mongodb:
        condition: service_healthy
      kafka:
        condition: service_healthy  
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    networks:
      - certification-service-network

  mongodb:
    image: mongo:latest
    container_name: certification_mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=rootpassword123
      - MONGO_INITDB_DATABASE=certificate_db
      - MONGO_COLLECTION_NAME=student_certificates
      - MONGO_USERNAME=certification_service
      - MONGO_PASSWORD=userpassword123
      - MONGO_DATABASE=certificate_db
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./mongodb/mongod.conf:/etc/mongod.conf
    healthcheck:
      test: mongosh --quiet --eval "db.adminCommand('ping')"
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - certification-service-network

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181" 
    networks:
      - certification-service-network

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: teachme-certification-service-kafka-1
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    healthcheck:
      test: ["CMD", "kafka-topics", "--bootstrap-server", "localhost:9092", "--list"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - certification-service-network

  azurite:
    container_name: azurite
    image: mcr.microsoft.com/azure-storage/azurite:3.33.0
    environment:
      - AZURE_STORAGE_ACCOUNT_NAME=devstoreaccount1
      - AZURE_STORAGE_ACCOUNT_KEY=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==
      - BLOB_STORAGE_CONTAINER_NAME=certificates
      - BLOB_STORAGE_CONNECTION_STRING=DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://azurite:10000/devstoreaccount1;
    expose:
      - 10000
      - 10001
      - 10002
    ports:
      - "10000:10000"
      - "10001:10001"
      - "10002:10002"
    volumes:
      - blob-storage-volume:/data
    networks:
      - certification-service-network
      
  test_runner:
    build: 
      context: . 
      dockerfile: Dockerfile.test
    depends_on:
      - azurite
      - app
    environment:
      - MONGO_DATABASE=certificate_db
      - MONGO_PORT=27017
      - MONGO_HOST=mongodb
      - MONGO_COLLECTION_NAME=student_certificates
      - MONGO_USERNAME=certification-service
      - MONGO_PASSWORD=userpassword123
      - AZURE_STORAGE_ACCOUNT_NAME=devstoreaccount1
      - AZURE_STORAGE_ACCOUNT_KEY=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==
      - BLOB_STORAGE_CONTAINER_NAME=certificates
      - BLOB_STORAGE_CONNECTION_STRING=DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://azurite:10000/devstoreaccount1;
      - CERTIFICATES_DIR=/app/certificates
      - PFX_PASSPHRASE=mysecurepassphrase
      - SIGNATURE_FIELD_NAME=Signature1
      - SIGNATURE_BOX=150,30,450,90
      - QR_CODE_URL=https://www.youtube.com/watch?v=dQw4w9WgXcQ
      - MONGODB_URI_ADMIN=mongodb://admin:rootpassword123@mongodb:27017/certificate_db?authSource=admin
      - MONGODB_URI_USER=mongodb://certification_service:userpassword123@mongodb:27017/certificate_db
    volumes:
      - ./certification_service:/app/certification_service
      - ./tests:/app/tests
      - ./certificates:/app/certificates
    networks:
      - certification-service-network
    command: pytest tests/test_api.py


volumes:
  kafka_data:
  zookeeper_data:
  blob-storage-volume:
  mongodb_data:
    driver: local

networks:
  certification-service-network:
    driver: bridge
