swagger: "2.0"
info:
  description: "Certify a student by generating a PDF certificate."
  version: "1.0.0"
  title: "Certify Student API"
paths:
  /api/v1/certify:
    post:
      summary: "Certify a student"
      description: "Generate a certificate for a student."
      parameters:
        - in: "body"
          name: "body"
          description: "Student and course data"
          required: true
          schema:
            type: "object"
            properties:
              student_id:
                type: "string"
              student_userId:
                type: "string"
              student_name:
                type: "string"
              student_surname:
                type: "string"
              student_email:
                type: "string"
              course_id:
                type: "string"
              course_name:
                type: "string"
              course_description:
                type: "string"
              course_duration:
                type: "string"
              course_level:
                type: "string"
              completionDate:
                type: "string"
                format: "date"
      responses:
        201:
          description: "Certificate created successfully"
        409:
          description: "Certificate already exists"
        400:
          description: "Invalid data supplied"
