swagger: "2.0"
info:
  description: "Delete a specific certificate for a student."
  version: "1.0.0"
  title: "Delete Course Certificate API"
paths:
  /api/v1/certificates/{student_id}/{course_id}:
    delete:
      summary: "Delete a certificate"
      description: "Delete a specific certificate for the given course and student."
      parameters:
        - name: "student_id"
          in: "path"
          required: true
          type: "string"
        - name: "course_id"
          in: "path"
          required: true
          type: "string"
      responses:
        200:
          description: "Certificate deleted successfully"
        400:
          description: "Deletion failed"
