swagger: "2.0"
info:
  description: "Delete all certificates for a student."
  version: "1.0.0"
  title: "Delete All Student Certificates API"
paths:
  /api/v1/certificates/{student_id}:
    delete:
      summary: "Delete all certificates"
      description: "Remove all certificates for the specified student."
      parameters:
        - name: "student_id"
          in: "path"
          required: true
          type: "string"
      responses:
        200:
          description: "Certificates deleted successfully"
        404:
          description: "No certificates found"
