swagger: "2.0"
info:
  description: "Retrieve all certificates for a student."
  version: "1.0.0"
  title: "Get All Student Certificates API"
paths:
  /api/v1/certificates/{student_id}:
    get:
      summary: "Get all certificates"
      description: "Fetch all certificates for a given student ID."
      parameters:
        - name: "student_id"
          in: "path"
          required: true
          type: "string"
          description: "ID of the student"
      responses:
        200:
          description: "A list of certificates"
        404:
          description: "No certificates found"
