---
swagger: '2.0'
info:
  title: "Get All Certificates API"
  description: "Retrieve all certificates for a student."
  version: "1.0.0"
paths:
  /api/v1/certificates/{student_id}:
    get:
      tags:
        - "Certification"
      summary: "Get all certificates for a student"
      description: "Retrieve all certificates for a student."
      parameters:
        - name: "student_id"
          in: "path"
          required: true
          type: "integer"
          format: "int64"
      responses:
        200:
          description: "Certificates retrieved successfully"
        404:
          description: "No certificates found or student not found"
