swagger: "2.0"
info:
  description: "Get a certificate for a specific course and student."
  version: "1.0.0"
  title: "Get Course Certificate API"
paths:
  /api/v1/certificates/{student_id}/{course_id}:
    get:
      summary: "Get a specific certificate"
      description: "Retrieve a certificate for a specific course and student."
      parameters:
        - name: "student_id"
          in: "path"
          required: true
          type: "string"
        - name: "course_id"
          in: "path"
          required: true
          type: "string"
      responses:
        200:
          description: "Certificate details"
        404:
          description: "Certificate not found"
