name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m venv test_venv
        source test_venv/bin/activate
        pip install --upgrade pip
        pip install -r requirements.txt

    - name: Lint with pylint
      id: pylint
      run: |
        source test_venv/bin/activate
        pip install pylint
        pylint certification_service > pylint_report.txt || true
        pylint_score=$(tail -n 2 pylint_report.txt | head -n 1 | awk '{print $7}')
        echo "Pylint score: $pylint_score"
        if (( $(echo "$pylint_score < 9.5" | bc -l) )); then
          echo "Pylint score is below 9.5, failing..."
          exit 1
        fi

    - name: Run tests
      run: |
        source test_venv/bin/activate
        pytest tests